# Generated by Django 5.0.3 on 2025-11-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tag_name")),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Task_name")),
                (
                    "content",
                    models.TextField(
                        blank=True, null=True, verbose_name="Task_content"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="Deadline"),
                ),
                ("is_done", models.BooleanField(default=False, verbose_name="Done")),
                (
                    "tags",
                    models.ManyToManyField(related_name="tasks", to="todo_app.tag"),
                ),
            ],
        ),
    ]
